new clean up code
savantly-net/sprout-platform pull request #150
Opened 2021-12-01 15:01 UTC by ketankanhasoft

2021-12-01 15:09 UTC, ketankanhasoft commented
Hi jeremy 

I created pull request for this, it contain lot of files.

https://github.com/savantly-net/sprout-platform/pull/150

2021-12-01 15:43 UTC, jdbranham commented on frontend/apps/webapp/src/core/components/Branding/BrandingProvider.tsx
> +// import axios, { AxiosResponse } from 'axios';
Let's delete, instead of commenting out the line.  
If we need to, we can view the history of the file to see the old code.

2021-12-01 15:44 UTC, jdbranham commented on frontend/apps/webapp/src/core/components/Branding/BrandingProvider.tsx
> +// import { StyleMatchType } from './brandingService';
Same for all the other lines we have commented out.  
Let's delete them to clean up the source.  
If we need to see the history, it's available in Git

2021-12-01 15:44 UTC, jdbranham commented on frontend/apps/webapp/src/core/components/FormikTags/index.tsx
> +// import { Select } from '@chakra-ui/react';
Delete

2021-12-01 15:45 UTC, jdbranham commented on frontend/apps/webapp/src/core/components/FormikTextInput/index.tsx
delete

2021-12-01 15:45 UTC, jdbranham commented on frontend/apps/webapp/src/core/components/ModalProxy/ModalProxy.tsx
> +// import LifecycleLogging from '../LifecycleLogging/LifecycleLogging';
delete

2021-12-01 15:45 UTC, jdbranham commented on frontend/apps/webapp/src/features/dashboard/components/AddPanelWidget/AddPanelWidget.tsx
> +// import { LocationUpdateService } from '../../../../core/services/locationSvc';
delete

2021-12-01 15:45 UTC, jdbranham commented on frontend/apps/webapp/src/features/dashboard/components/DashNav/DashNav.tsx
> +  // const { dashboard, isFullscreen } = props;
delete

2021-12-01 15:46 UTC, jdbranham commented on frontend/apps/webapp/src/features/dashboard/components/PanelEditor/PanelEditor.tsx
> +    // const { dashboard, uiState } = this.props;
delete

2021-12-01 15:46 UTC, jdbranham commented on frontend/apps/webapp/src/features/dashboard/components/PanelEditor/PanelEditorTabs.tsx
> +  // const activeTab = tabs.find(item => item.active)!;
delete

2021-12-01 15:46 UTC, jdbranham commented on frontend/apps/webapp/src/features/dashboard/components/PanelEditor/state/selectors.ts
> +// import { getConfig } from '../../../../../core/config';
delete

2021-12-01 15:47 UTC, jdbranham commented on frontend/apps/webapp/src/features/dashboard/components/SubMenu/SubMenu.tsx
> +    // const { dashboard } = this.props;
delete

2021-12-01 15:47 UTC, jdbranham commented on frontend/apps/webapp/src/features/dashboard/containers/DashboardProvider.tsx
> +// };
delete

2021-12-01 15:47 UTC, jdbranham commented on frontend/apps/webapp/src/features/dashboard/dashgrid/DashboardGrid.tsx
> +// import { Spinner } from 'reactstrap';
delete

2021-12-01 15:47 UTC, jdbranham commented on frontend/apps/webapp/src/features/dashboard/dashgrid/PanelChrome.tsx
> +    // const { panel, isInView, width } = this.props;
delete

2021-12-01 15:48 UTC, jdbranham commented on frontend/apps/webapp/src/features/feedback/item/editor.tsx
> +// };
delete

2021-12-01 15:48 UTC, jdbranham commented on frontend/apps/webapp/src/features/menu/DragAndDropMenuBuilder/DraggableMenuItem/MenuItem/index.tsx
> +// import { FormField } from '@sprout-platform/ui';
delete

2021-12-01 15:48 UTC, jdbranham commented on frontend/apps/webapp/src/features/menu/DragAndDropMenuBuilder/index.tsx
> +// import { DialogModalCloseResponse } from '../../../core/components/ChakraDialogModal';
delete

2021-12-01 15:49 UTC, jdbranham commented on frontend/apps/webapp/src/features/menu/DragAndDropMenuBuilder/index.tsx
> +// }
delete

2021-12-01 15:49 UTC, jdbranham commented on frontend/apps/webapp/src/features/menu/MenuAdminPage.tsx
> +    // const response = await menuAdminService.deleteMenu(menuItem);
delete

2021-12-01 15:49 UTC, jdbranham commented on frontend/apps/webapp/src/features/navigation/navTree.ts
> +// }
delete

2021-12-01 15:50 UTC, jdbranham commented on frontend/apps/webapp/src/features/plugins/PluginListPage.tsx
> +    // };
delete

2021-12-01 15:50 UTC, jdbranham commented on frontend/apps/webapp/src/features/remoteContentViewer/index.tsx
> +// }
delete

2021-12-01 15:50 UTC, jdbranham commented on frontend/apps/webapp/src/plugins/panel/query/QueryPanel.tsx
> +  // const [error, setError] = useState('');
delete

2021-12-01 15:50 UTC, jdbranham commented on frontend/apps/webapp/src/plugins/panel/query/editors/QueryParametersEditor.tsx
> +  // const [state, setState] = useState(value);
delete

2021-12-01 15:51 UTC, jdbranham commented on frontend/apps/webapp/src/plugins/panel/query/editors/TemplateEditor.tsx
> +  // console.log('state value', state);
delete

2021-12-01 15:51 UTC, jdbranham commented on frontend/apps/webapp/src/plugins/panel/table/TablePanel.tsx
> +// import { CustomScrollbar, stylesFactory } from '@savantly/sprout-ui';
delete

2021-12-01 15:51 UTC, jdbranham commented on frontend/apps/webapp/src/plugins/panel/table/TablePanel.tsx
> +  // const { setFieldValue, values } = useFormikContext();
delete

2021-12-01 15:51 UTC, jdbranham commented on frontend/apps/webapp/src/plugins/panel/table/TablePanel.tsx
> +  // const [error, setError] = useState('');
delete

2021-12-01 15:51 UTC, jdbranham commented on frontend/apps/webapp/src/plugins/panel/table/TablePanel.tsx
> +  // const styles = getStyles();
delete

2021-12-01 15:52 UTC, jdbranham commented on frontend/apps/webapp/src/plugins/panel/table/TablePanel.tsx
> +// });
delete

2021-12-01 15:52 UTC, jdbranham commented on frontend/apps/webapp/src/plugins/panel/table/editors/QueryParametersEditor.tsx
> +  // const [state, setState] = useState(value);
delete

2021-12-01 15:52 UTC, jdbranham commented on frontend/apps/webapp/src/plugins/panel/table/editors/TemplateEditor.tsx
> +  // console.log('state value', state);
delete

2021-12-01 15:52 UTC, jdbranham requested changes
Some minor cleanup to remove commented out code

2021-12-06 15:09 UTC, ketankanhasoft commented
I deleted this comment codes, please let me know if anything is missing.

2021-12-06 16:06 UTC, merged